version: '3.8'

services:
  # maven:
  #   build:
  #     context: .
  #     dockerfile: ./maven.dockerfile
  #   command: tail -f /dev/null
  #   networks:
  #     - sonarqube-network

  sonarqube:
    build:
      context: .
      dockerfile: ./sonarqube.dockerfile
    command: tail -f /dev/null
    ports:
      - "9000:9000"
    networks:
      - sonarqube-network

  # nexus:
  #   build:
  #     context: .
  #     dockerfile: ./nexus.dockerfile
  #   command: tail -f /dev/null
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - sonarqube-network

  # gradle:
  #   build:
  #     context: .
  #     dockerfile: ./gradle.dockerfile
  #   command: tail -f /dev/null
  #   networks:
  #     - sonarqube-network

  # jenkins:
  #   build:
  #     context: .
  #     dockerfile: ./jenkins.dockerfile
  #   command: tail -f /dev/null
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - sonarqube-network

  ci-server:
    build:
      context: .
      dockerfile: ./ci-server.dockerfile
    command: tail -f /dev/null
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
